SELECT
	VERSION();
	

CREATE DATABASE IF NOT EXISTS movie_capstone;

USE movie_capstone;

CREATE TABLE IF NOT EXISTS `Phim` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenPhim`  VARCHAR(255),
	`trailer` VARCHAR(255),
	`hinhAnh` VARCHAR(255),
	`moTa` VARCHAR(255),
	`ngayKhoiChieu` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`danhGia` INT NOT NULL DEFAULT 0,
	`hot` TINYINT(1) NOT NULL DEFAULT 0,
	`dangChieu` TINYINT(1) NOT NULL DEFAULT 0,
	`sapChieu` TINYINT(1) NOT NULL DEFAULT 0,
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `Banner` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`hinhAnh` VARCHAR(255),
	`maPhim` INT NOT NULL,
	FOREIGN KEY (`maPhim`) REFERENCES `Phim` (`id`),
	
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `HeThongRap` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenHeThongRap` VARCHAR(255),
	`logo` VARCHAR(255),
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `CumRap` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenCumRap` VARCHAR(255),
	`diaChi` VARCHAR(255),
	`maHeThongRap` INT NOT NULL,
	FOREIGN KEY (`maHeThongRap`) REFERENCES `HeThongRap` (`id`),
	
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `RapPhim` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenRap` VARCHAR(255),
	`maCumRap` INT NOT NULL,
	FOREIGN KEY (`maCumRap`) REFERENCES `CumRap` (`id`),
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS `Ghe` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenGhe` VARCHAR(255),
	`loaiGhe` VARCHAR(255),
	`maRap` INT NOT NULL,
	FOREIGN KEY (`maRap`) REFERENCES `RapPhim` (`id`),
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `LichChieu` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`maRap` INT NOT NULL,
	`maPhim` INT NOT NULL,
	`giaVe` INT,
	`ngayGioChieu` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`maRap`) REFERENCES `RapPhim` (`id`),
	FOREIGN KEY (`maPhim`) REFERENCES `Phim` (`id`),
	
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `LoaiNguoiDung` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`tenLoai` VARCHAR(255),
	`moTa` VARCHAR(255),
	`isActive` BOOL DEFAULT 1,
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `NguoiDung` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`hoTen` VARCHAR(255),
	`email` VARCHAR(255) UNIQUE,
	`phone` VARCHAR(255),
	`password` VARCHAR(255),
	`maLoaiNguoiDung` INT NOT NULL DEFAULT 2,
	`facebookId` VARCHAR(255) UNIQUE,
	`googleId` VARCHAR(255) UNIQUE,
	FOREIGN KEY (`maLoaiNguoiDung`) REFERENCES `LoaiNguoiDung` (`id`),
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS `DatVe` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`maNguoiDung` INT NOT NULL,
	`maLichChieu` INT NOT NULL,
	`maGhe` INT NOT NULL,
	FOREIGN KEY (`maNguoiDung`) REFERENCES `NguoiDung` (`id`),
	FOREIGN KEY (`maLichChieu`) REFERENCES `LichChieu` (`id`),
	FOREIGN KEY (`maGhe`) REFERENCES `Ghe` (`id`),
	-- mặc định luôn luôn có
	-- mặc định luôn luôn có
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
